server:
  port: 8082

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/microservices
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelmicroservicedb
    username: root
    password: root
  #    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: HOTEL-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true